name: Go

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      package: src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/${{ env.package }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.0"
          cache-dependency-path: |
            ${{ env.GOPATH }}/${{ env.package }}/go.mod
            ${{ env.GOPATH }}/${{ env.package }}/go.sum

      - name: Dependencies
        run: go mod download

      - name: Build
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
        run: go build -v ./...

      - name: Test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
        run: go test -v ./...
